#!/usr/bin/python

# FIXME
import sys
sys.path[0] += "/lib"

from pyradm import Help, Config
from pyradm.utils import yes
from pyradm.UI import CLI 

Help["usage"] = """
Usage: pyradm [options]
        -m, -maintain           maintenance mode; don't connect to server
        -c, -config <filename>  use config file other than $HOME/.pyradmrc
        -h, -help               print help text
"""

try:
  Config.Options().getopt()

  if Config.Options()["help"]:
    print Help["usage"]
  else:
    CLI.UI().run()

except Config.OptionsException, e:
  print "ERROR: %s" % (e)
  print Help["usage"]

except Config.ParseException, e:
  print "ERROR: %s" % (e)

# vim:ts=2:sw=2:et
