#!/usr/bin/python

# FIXME
import sys
sys.path[0] += "/lib"

from pyradm import Help, Config, Options, ConfigFileException, OptionsException, QuitException
from pyradm.utils import yes
from pyradm.UI import CLI 

Help["usage"] = """
Usage: pyradm [options]
        -m, -maintain           maintenance mode; don't connect to server
        -c, -config <filename>  use config file other than $HOME/.pyradmrc
        -h, -help               print help text
"""

try:
  options = Options()

  if options["help"]:
    print Help["usage"]
  else:
    try:
      config = Config(options["config"])
    except ConfigFileException:
      if yes("Config file %s don't exists.\nDo you want to run maintenance mode to create it?" % (options["config"])):
        options["maintain"] = True
      else:
        raise QuitException()
      
    ui = CLI(Config(options["config"], options["maintain"]))
    ui.run()

except OptionsException, e:
  print e
except QuitException: pass

# vim:ts=2:sw=2:et
