#!/usr/bin/python

# FIXME 
import sys
sys.path[0] += "/lib"

from pyradm import Help, Config, Options
from pyradm.UI import CLI 

Help["usage"] = """
Usage: pyradm [options]
        -m, -maintain           maintenance mode; don't connect to server
        -c, -config <filename>  use config file other than $HOME/.pyradmrc
        -h, -help               print help text
"""

try:
  if Options()["help"]:
    print Help["usage"]
  else:
    CLI().run()

except e:
  print "ERROR: %s" % (e)
  print Help["usage"]

# vim:ts=2:sw=2:et
